tts_data = [   ('[KienThucQuanSu]Điều gì xảy ra ở Bắc Cực không ở lại Bắc Cực.', 'audio_VN/0.wav'),
    ('[KienThucQuanSu]Có những điều đang diễn ra ở Bắc Cực mà có lẽ đã 20 năm trước rồi.', 'audio_VN/1.wav'),
    ('[KienThucQuanSu]Đây là vùng ấm lên nhanh hơn bất cứ nơi nào khác.', 'audio_VN/2.wav'),
    ('[KienThucQuanSu]và khi khí hậu thay đổi,', 'audio_VN/3.wav'),
    ('[KienThucQuanSu]Nó cũng quan trọng như vậy.', 'audio_VN/4.wav'),
    ('[KienThucQuanSu]Chúng ta cần toàn cầu cho an ninh quốc gia và thậm chí cả an ninh quốc tế.', 'audio_VN/5.wav'),
    (   '[KienThucQuanSu]* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *',
        'audio_VN/6.wav'),
    (   '[KienThucQuanSu]tìm kiếm nguồn tài nguyên, băng qua băng và một cách để củng cố vị trí của họ trên toàn cầu.',
        'audio_VN/7.wav'),
    ('[KienThucQuanSu]Rất nhiều quốc gia đã đi ra ngoài cùng với vi khuẩn.', 'audio_VN/8.wav'),
    ('[KienThucQuanSu]Nó là một phần của trật tự quốc tế đang bị thách thức như thế nào.', 'audio_VN/9.wav'),
    (   '[KienThucQuanSu]Đây là năm lý do tại sao Bắc Cực đã trở thành một trong những vùng được tranh luận nóng nhất '
        'thế giới.',
        'audio_VN/10.wav'),
    ('[KienThucQuanSu]Để hiểu được điều này, chúng ta cần nhìn thế giới theo một cách khác.', 'audio_VN/11.wav'),
    ('[KienThucQuanSu]Không chỉ là một đại dương băng hà, tám quốc gia có lãnh thổ trong...', 'audio_VN/12.wav'),
    (   '[KienThucQuanSu]Hoa Kỳ, Canada, Greenland, là một vùng bán tự do của Đan Mạch, Iceland, Thụy Điển, Phần Lan, '
        'và Nga.',
        'audio_VN/13.wav'),
    ('[KienThucQuanSu]Trong thời chiến tranh lạnh giữa Mỹ và Liên Xô,', 'audio_VN/14.wav'),
    ('[KienThucQuanSu]vượt qua cột là một tuyến đường phóng hỏa tiễn.', 'audio_VN/15.wav'),
    ('[KienThucQuanSu]Các quốc gia tham gia hoạt động quân sự của họ,', 'audio_VN/16.wav'),
    ('[KienThucQuanSu]với Hoa Kỳ một căn cứ ở phía bắc của Greenland.', 'audio_VN/17.wav'),
    ('[KienThucQuanSu]Nhưng vào năm 1987, khi Chiến Tranh Lạnh sắp kết thúc,', 'audio_VN/18.wav'),
    ('[KienThucQuanSu]Sau khi đã được giải quyết', 'audio_VN/19.wav'),
    ('[KienThucQuanSu]trong quân đội ở Bắc Cực.', 'audio_VN/20.wav'),
    ('[KienThucQuanSu]Điều mà Gorbach đã cố gắng để làm là một ảo ảnh', 'audio_VN/21.wav'),
    ('[KienThucQuanSu]nơi mà Bắc Cực đã đi qua.', 'audio_VN/22.wav'),
    ('[KienThucQuanSu]tập trung vào những khu vực có thể tìm ra nguyên nhân chung.', 'audio_VN/23.wav'),
    ('[KienThucQuanSu]Trong những năm sau đó, tám mươi tám quốc gia đã hợp thành Bắc Bắc Bắc', 'audio_VN/24.wav'),
    ('[KienThucQuanSu]đồng ý làm việc cùng nhau về nghiên cứu và môi trường.', 'audio_VN/25.wav'),
    ('[KienThucQuanSu]Các tiểu bang Bắc và Bắc cực không phải là vô điều kiện đã làm nghiên cứu', 'audio_VN/26.wav'),
    (   '[KienThucQuanSu]Các quốc gia như Trung Quốc, Hoa Kỳ và Hàn và Hàn và Hàn Quốc về cách các khu vực tác động',
        'audio_VN/27.wav'),
    ('[KienThucQuanSu]Các mô hình', 'audio_VN/28.wav'),
    ('[KienThucQuanSu]cách đó hàng ngàn dặm ở châu Á.', 'audio_VN/29.wav'),
    ('[KienThucQuanSu]Các đã có điều này đã có của', 'audio_VN/30.wav'),
    ('[KienThucQuanSu]Kiểu như một nơi bình yên và hợp tác đặc biệt.', 'audio_VN/31.wav'),
    ('[KienThucQuanSu]Câu chuyện đó kéo dài cho đến khi Nga chiếm đóng...', 'audio_VN/32.wav'),
    ('[KienThucQuanSu]Năm 2022, Nga mở đầu Chiến Tranh Lạnh.', 'audio_VN/33.wav'),
    (   '[KienThucQuanSu]Trong vòng vài tháng, Phần Lan và Thụy Điển đã đăng ký nhập ngũ với NATO, quân đội Tây '
        'phương.',
        'audio_VN/34.wav'),
    ('[KienThucQuanSu]Bản đồ đã trở thành Nga ở một bên và các thành viên.', 'audio_VN/35.wav'),
    ('[KienThucQuanSu]Giới biên giới giữa Trung Hải, Phần mở và Nga là ranh giới của Nga và Nga', 'audio_VN/36.wav'),
    ('[KienThucQuanSu]- Chào.', 'audio_VN/37.wav'),
    (   '[KienThucQuanSu]Những trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực trực '
        'trực trực trực trực trực trực trực trực trực trực trực trực trực trực',
        'audio_VN/38.wav'),
    ('[KienThucQuanSu]khi một căn cứ không quân Nga ở Bắc Cực bị tấn công bởi một...', 'audio_VN/39.wav'),
    ('[KienThucQuanSu]Khu vực này phụ thuộc vào quân đội Nga.', 'audio_VN/40.wav'),
    ('[KienThucQuanSu]Phần lớn nguyên nguyên nguyên hạt hạt của nó là dựa vào người Nga', 'audio_VN/41.wav'),
    ('[KienThucQuanSu]Tôi không biết.', 'audio_VN/42.wav'),
    ('[KienThucQuanSu]Chúng tôi sẽ nhìn thấy bạn trong video tiếp theo.', 'audio_VN/43.wav'),
    ('[KienThucQuanSu]Nó chỉ cho chúng ta biết về gia đình cầu nguyện này', 'audio_VN/44.wav'),
    ('[KienThucQuanSu]Nước Nga đã mở cửa hàng chục...', 'audio_VN/45.wav'),
    ('[KienThucQuanSu]và được sử dụng trong tích cực.', 'audio_VN/46.wav'),
    ('[KienThucQuanSu]Tăng nhịp tim.', 'audio_VN/47.wav'),
    ('[KienThucQuanSu]Các máy bay chiến đấu của Nga và Mỹ đã đến rất gần trên bầu trời gần Alaska.', 'audio_VN/48.wav'),
    ('[KienThucQuanSu]phương tây cũng mở rộng.', 'audio_VN/49.wav'),
    ('[KienThucQuanSu]20 mũi khoan lớn nhất của hắn trong khu vực kể từ khi trời lạnh.', 'audio_VN/50.wav'),
    ('[KienThucQuanSu]Quân đội Hoa Kỳ đã tái lập lực lượng đặc biệt.', 'audio_VN/51.wav'),
    ('[KienThucQuanSu]Tổng thống T-Ty đã đề nghị một điều gì đó táo bạo.', 'audio_VN/52.wav'),
    ('[KienThucQuanSu]Chúng ta cần toàn cầu cho an ninh quốc gia và an ninh quốc tế.', 'audio_VN/53.wav'),
    ('[KienThucQuanSu]Nên tôi nghĩ chúng ta sẽ đi càng xa càng tốt.', 'audio_VN/54.wav'),
    ('[KienThucQuanSu]Chúng ta cần Greenland và thế giới cần chúng ta có.', 'audio_VN/55.wav'),
    ('[KienThucQuanSu]Hoa Kỳ vẫn có một căn cứ quân sự trong khu căn cứ.', 'audio_VN/56.wav'),
    ('[KienThucQuanSu]Và câu trả lời cho lời đề nghị của ông Tir...', 'audio_VN/57.wav'),
    (   '[KienThucQuanSu]Các cuộc thăm thăm thăm gợi gợi gợi khuyên nhiều người không muốn là một phần của',
        'audio_VN/58.wav'),
    ('[KienThucQuanSu]đa muốn được độc lập.', 'audio_VN/59.wav'),
    (   '[KienThucQuanSu]Đối với Donald Tmp, một sự hiện diện đặc biệt ở Bắc Cực là chìa khóa để chống lại các đối tác',
        'audio_VN/60.wav'),
    ('[KienThucQuanSu]giữa Nga và Trung Quốc, hai quốc gia miêu tả tình bạn không giới hạn.', 'audio_VN/61.wav'),
    ('[KienThucQuanSu]Anh thậm chí còn không cần.', 'audio_VN/62.wav'),
    ('[KienThucQuanSu]Các người nhìn ra ngoài, các người có Trung Quốc, các chiến hạm.', 'audio_VN/63.wav'),
    ('[KienThucQuanSu]Anh có nhiều thuyền Nga khắp nơi.', 'audio_VN/64.wav'),
    ('[KienThucQuanSu]Chúng ta sẽ không để điều đó xảy ra.', 'audio_VN/65.wav'),
    (   '[KienThucQuanSu]Hải quân Nga và Hải quân Trung Quốc đã thực hiện các tuần tra chung ở Bắc Cực.',
        'audio_VN/66.wav'),
    ('[KienThucQuanSu]Những kẻ đánh bom từ cả hai quốc gia đã tập hợp lại với nhau.', 'audio_VN/67.wav'),
    ('[KienThucQuanSu]Đây là lần đầu tiên chúng ta thấy hai quốc gia này cùng nhau bay như thế.', 'audio_VN/68.wav'),
    ('[KienThucQuanSu]Chiến tranh là...', 'audio_VN/69.wav'),
    ('[KienThucQuanSu]vài bài tập, bài huấn luyện, tuần tra.', 'audio_VN/70.wav'),
    ('[KienThucQuanSu]& mời', 'audio_VN/71.wav'),
    ('[KienThucQuanSu]một sai lầm.', 'audio_VN/72.wav'),
    ('[KienThucQuanSu]Trung Quốc nói quy định của nó là liên quan đến sự hợp nhất', 'audio_VN/73.wav'),
    ('[KienThucQuanSu]và không có ở xa', 'audio_VN/74.wav'),
    ('[KienThucQuanSu]Tuy nhiên, điều này', 'audio_VN/75.wav'),
    ('[KienThucQuanSu]Có một mối nguy hiểm mà Nga đã biết rõ', 'audio_VN/76.wav'),
    ('[KienThucQuanSu]đó là càng ngày càng nhiều nó tương đương với Trung Quốc,', 'audio_VN/77.wav'),
    ('[KienThucQuanSu]Càng nhiều thì nó càng cho Trung Quốc.', 'audio_VN/78.wav'),
    ('[KienThucQuanSu]là một bước rất mạnh mẽ, gần cực.', 'audio_VN/79.wav'),
    ('[KienThucQuanSu]Mô tả bản chất giống như một gần-một...', 'audio_VN/80.wav'),
    ('[KienThucQuanSu]Mặc dù là từ Bắc Cực.', 'audio_VN/81.wav'),
    ('[KienThucQuanSu]Trong năm 2018, nó đã phát triển một phạm diện phạm vi của các khoản tiền', 'audio_VN/82.wav'),
    ('[KienThucQuanSu]nó được gọi là đường tơ.', 'audio_VN/83.wav'),
    ('[KienThucQuanSu]♪ Nhưng nó đã tấn công vào các chốt', 'audio_VN/84.wav'),
    ('[KienThucQuanSu]Về việc quá chú trọng vào việc này.', 'audio_VN/85.wav'),
    ('[KienThucQuanSu]Họ muốn trở thành một con người.', 'audio_VN/86.wav'),
    ('[KienThucQuanSu]Chúng tôi muốn...', 'audio_VN/87.wav'),
    (   '[KienThucQuanSu]họ phát phát phát phát về Trung hoa nhưng chúng tôi không muốn muốn muốn được trên',
        'audio_VN/88.wav'),
    (   '[KienThucQuanSu]Không có câu hỏi nào là nó đang cố gắng để sắp xếp để có một tác động quan trọng ở Bắc Cực,',
        'audio_VN/89.wav'),
    ('[KienThucQuanSu]nhưng nó không đến với hoa quả.', 'audio_VN/90.wav'),
    ('[KienThucQuanSu]Phần lớn thành công của nền kinh tế Trung Hoa...', 'audio_VN/91.wav'),
    ('[KienThucQuanSu]là từ hợp tác với...', 'audio_VN/92.wav'),
    ('[KienThucQuanSu]như thế này', 'audio_VN/93.wav'),
    (   '[KienThucQuanSu]và vận chuyển khí này đã được làm dễ dàng hơn bởi biển băng tan của Bắc Băng Dương.',
        'audio_VN/94.wav'),
    ('[KienThucQuanSu]Đây là số tiền có được vào mùa hè năm 1979.', 'audio_VN/95.wav'),
    ('[KienThucQuanSu]Và điều này không', 'audio_VN/96.wav'),
    ('[KienThucQuanSu]một tỷ lệ 2.62 triệu vuông.', 'audio_VN/97.wav'),
    ('[KienThucQuanSu]là kích thước của kích thước', 'audio_VN/98.wav'),
    ('[KienThucQuanSu]Nhiều người thấy đây là cơ hội để khai thác biển tàu trong suốt thời gian...', 'audio_VN/99.wav'),
    ('[KienThucQuanSu]Trong 3 tiềm năng, người duy nhất còn lại đang ở phía Bắc nước Nga.', 'audio_VN/100.wav'),
    (   '[KienThucQuanSu]đã biết y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y '
        'y y y y y y y y y y y y y y y y y y y y y y y y y',
        'audio_VN/101.wav'),
    ('[KienThucQuanSu]đã có hy vọng rằng càng ngày càng nhiều hơn', 'audio_VN/102.wav'),
    ('[KienThucQuanSu]có thể trên trên không qua khoảng cách kênh kênh kênh', 'audio_VN/103.wav'),
    ('[KienThucQuanSu]và hình dạng hàng ngàn dặm của thời gian và khoảng cách.', 'audio_VN/104.wav'),
    ('[KienThucQuanSu]Tàu chở hàng được thực hiện bằng tàu biển vào năm 2020.', 'audio_VN/105.wav'),
    ('[KienThucQuanSu]xuất khẩu từ Nga.', 'audio_VN/106.wav'),
    ('[KienThucQuanSu]Nhưng so với Suez, với 13.000 tàu đi qua mỗi năm, nó xa', 'audio_VN/107.wav'),
    ('[KienThucQuanSu]là một sự lựa chọn.', 'audio_VN/108.wav'),
    ('[KienThucQuanSu]Đại dương đóng băng gần hết năm.', 'audio_VN/109.wav'),
    ('[KienThucQuanSu]Ngay cả trong mùa hè, nó là một môi trường bất định.', 'audio_VN/110.wav'),
    ('[KienThucQuanSu]Bạn sẽ có một tình huống mà có rất nhỏ các cửa sổ thời gian', 'audio_VN/111.wav'),
    (   '[KienThucQuanSu]nơi có thể có có có thể có được t có thể có được t mối quan đến và mà không không cung không '
        'cung cấp',
        'audio_VN/112.wav'),
    ('[KienThucQuanSu]Chắc chắn là cần thiết cho việc phân phối tài sản.', 'audio_VN/113.wav'),
    ('[KienThucQuanSu]Trong khi chờ ghi nhớ về...', 'audio_VN/114.wav'),
    ('[KienThucQuanSu]Còn hơn cả băng tan.', 'audio_VN/115.wav'),
    (   '[KienThucQuanSu]Đã có một sự tường thuật về phần giới hạn cuối của các nguồn lực giàu có chưa từng có trong '
        'quá khứ.',
        'audio_VN/116.wav'),
    (   '[KienThucQuanSu]Đó là ước tính rằng 30% của các gas chưa được khám phá của thế giới và 13% của undist dầu',
        'audio_VN/117.wav'),
    ('[KienThucQuanSu]Cả thuốc cũng vậy, đặc biệt là ở Greenland.', 'audio_VN/118.wav'),
    ('[KienThucQuanSu]Nếu Hoa Kỳ có quyền truy cập vào nghiên cứu...', 'audio_VN/119.wav'),
    ('[KienThucQuanSu]Nó có thể giảm bớt sự bất hòa của chúng ta ở nước ngoài', 'audio_VN/120.wav'),
    ('[KienThucQuanSu]Gặp lỗi khi khởi động bộ phát âm...', 'audio_VN/121.wav'),
    ('[KienThucQuanSu]trên trái đất hiếm có.', 'audio_VN/122.wav'),
    ('[KienThucQuanSu]khi mà những thứ này...', 'audio_VN/123.wav'),
    ('[KienThucQuanSu]- Không, không.', 'audio_VN/124.wav'),
    ('[KienThucQuanSu]bạn đang làm việc với những môi trường được từ xa, đắt để', 'audio_VN/125.wav'),
    ('[KienThucQuanSu]Cơ sở hạ tầng và nơi có rất ít những công việc vô cùng hữu ích.', 'audio_VN/126.wav'),
    (   '[KienThucQuanSu]Bất chấp điều này, sự quan tâm toàn cầu đến khu vực, và lượng băng tan càng nhiều thì càng '
        'tiết lộ, vẫn còn.',
        'audio_VN/127.wav'),
    ('[KienThucQuanSu]và có thể giới thiệu với các bạn rằng chúng ta có thể nói về vấn đề này.', 'audio_VN/128.wav'),
    ('[KienThucQuanSu]15 năm trước, bạn đã có thể đã nhìn thấy', 'audio_VN/129.wav'),
    ('[KienThucQuanSu]Bắc Cực là một vùng đặc trưng tốt nhất được định vị bởi High North Lop.', 'audio_VN/130.wav'),
    ('[KienThucQuanSu]Bây giờ chúng ta nên mô tả điều đó.', 'audio_VN/131.wav'),
    ('[KienThucQuanSu]ở độ cao phía bắc.', 'audio_VN/132.wav')]
